# Generated by Django 5.2.13 on 2026-04-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('HACKATHON', 'Hackathon'), ('SIDE_PROJECT', 'Side Project'), ('RESEARCH', 'Research'), ('STARTUP', 'Startup')], default='SIDE_PROJECT', max_length=20)),
                ('required_skills', models.JSONField(default=list)),
                ('team_size', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
