# Generated by Django 5.2.13 on 2026-04-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
